### ISSUE TITLE
Can I use nodespeed-ide like the old way of bracket-servers?

### ISSUE THREAD

**Issue by dihuta** [whoGloo/nodespeed-ide#2]
Hi,

I'm using brackets-server on my Chromebook as main IDE for my project development.  I installed brackets-server globally by npm and use it like this:

`brackets --port 8000 --proj-dir ~/my-project/
`
Can I use nodespeed-ide like that? 
Thank you so much.

**Comment by asthomasdk** [comment]
Hi @dihuta , 

To be honest, I don't know, as we have not tried this. 

Our main focus on this projects has been to make use of the nodeSpeed IDE inside Docker containers as part of our hosted setup. But, you can also run it within Docker containers locally if you want. 

The main reason for using it in this way was to have pre-configured environments with mongodb and postgres services built into the container stack (can easily be extended with other databases and services if needed) - and also to have the file system with projects, extensions etc available in a data container for each user. 

If you look at the readme, there are instructions on how to get started with Docker containers-  even using a pre-built container that we have published to Docker Hub : `whogloo/nodespeed-ide`.

**Comment by dihuta** [comment]
The old brackets-server project was unmaintainced, it use brackets 1.3. So I'm looking for a new one that can support new version of brackets.

**Comment by asthomasdk** [comment]
We are currently using Brackets 1.8, and need to get it updated to 1.9. Just haven't had time to do so. 

I have been trying to limit the number of changes needed to the Brackets core - and hopefully we can make these go away completely at some stage. Right now, the build includes a forked version of the Brackets 1.8 release.

**Comment by asthomasdk** [comment]
I guess we can try and publish to npm as well and see if this works. But, as I have mentioned earlier, the main focus from our side has been to use this in containers to get away from stuff running directly on a pc or host.

**Comment by dihuta** [comment]
I'm sorry, I try new command,  is this an error?

```
node nodespeed-ide/nodespeedide -j ~/Downloads/me
teor/ -s ~/Downloads/meteor
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::6800
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at /home/chronos/user/Downloads/nodespeed-ide/nodespeedide.js:238:12
    at Object.<anonymous> (/home/chronos/user/Downloads/nodespeed-ide/nodespeedide.js:242:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by dihuta** [comment]
Sorry, there is another process is running. This is not a bug.
Thank you.
