### ISSUE TITLE
nodeSpeed build error

### ISSUE THREAD

**Issue by dihuta** [whoGloo/nodespeed-ide#3]
I follow these step to build nodespeed. 
```
$ git clone https://github.com/whoGloo/nodespeed-ide.git
    $ cd brackets-server
    $ git submodule update --recursive --init
    $ npm install
    $ grunt build
```

At "grunt build" command, I receive this error:
```
Tracing dependencies for: main
Error: ENOENT: no such file or directory, open '/home/chronos/user/Downloads/nodespeed-ide/embedded-ext/brackets-file-upload/node_modules/async/dist/async.js'
In module tree:
    main

{ Error: Error: ENOENT: no such file or directory, open '/home/chronos/user/Downloads/nodespeed-ide/embedded-ext/brackets-file-upload/node_modules/async/dist/async.js'
In module tree:
    main

    at Error (native)

    at /home/chronos/user/Downloads/nodespeed-ide/node_modules/requirejs/bin/r.js:30099:19
   ...
```

My system: Linux x86_64

**Comment by dihuta** [comment]
Try install async and found another missing package.
```Tracing dependencies for: main
Error: ENOENT: no such file or directory, open '/home/chronos/user/Downloads/nodespeed-ide/embedded-ext/brackets-nodespeed-custom/node_modules/clipboard-js/clipboard.js'
In module tree:
    main
```

**Comment by asthomasdk** [comment]
I may have some incomplete updates that need to be pushed to this after trying to add our  suggested extensions as embedded extensions. 

Try running `npm install` inside each of the embedded-ext sub directories. That may help.

**Comment by asthomasdk** [comment]
I'll have a look at this tomorrow and see if I can get this sorted out. We may need to remove the embedded extensions for now and you can then install the ones you want to use afterwards. Something with the embedded extensions is breaking the build...

**Comment by dihuta** [comment]
OK, Thanks.
Please update this conversation when you complete update. I will clone and try again.

**Comment by asthomasdk** [comment]
I've just pushed a couple of updates which remove the custom embedded extensions for now. 

Feel free to try a new clone and build. 

There should also be a new docker build available a little later when the build has had time to complete.

**Comment by dihuta** [comment]
Chrome OS doesn't support Docker. I have to build and run by node command.

**Comment by dihuta** [comment]
The build process now works ver smoothly.

**Comment by dihuta** [comment]
I can not run the lasted build, new error:

```
node bin/run  -j ~/Downloads/new -s ~/Downloads/new

  listening on port 6800

/home/chronos/user/Downloads/nodespeed-ide/lib/server.js:46
    inst.app.get('/brackets',function(req,res,next) {
            ^

TypeError: Cannot read property 'get' of undefined
    at attachStatic (/home/chronos/user/Downloads/nodespeed-ide/lib/server.js:46:13)
    at /home/chronos/user/Downloads/nodespeed-ide/lib/server.js:172:9
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by asthomasdk** [comment]
That would be because bin/run is not the right one to be running here. 

Try: 

`node nodespeedide --supp-dir /projects/.brackets-server -j /projects`

As per the readme ;-)
