### ISSUE TITLE
Just trying to figure out what kind of functionality this actually has.

### ISSUE THREAD

**Issue by haddow777** [whoGloo/nodespeed-ide#6]
Hello, I recently came across this project after looking into brackes-server and finding out it isn't supported anymore. Anyways, it seems like a great idea, but Iam getting the feeling after long hours of trying to install it properly that it isn't very functional.
Is this an alpha stage project? I can't see any way of getting a live view of the project (basically an index.html file I created). In fact, I can't find any way of actually getting the index.html file to load into my browser at all. I've tried all the ports that your docs use during the docker setup. One gives me the ide, the other gives me the xterm that the ide can't seem to pull up, and the other two do nothing.
Also, it can't install extensions through the extension manager.
I tried to go to the spinup site to see how a version of this that is completely built and setup works, but the site isn't working.
I'm not trying to complain, I just want an idea of what sort of functionality this thing is actually supposed to have working right now. There must be a way to load the files created in the project into a browser to see them. Otherwise, what's the point.
Thank you.

**Comment by haddow777** [comment]
Oh, by the way, I cloned it down onto my remote server and built the docker image instead of pulling it down. I started out by pulling it down, but when it wasn't working, I changed. I installed the brackets-nodespeed-custom extension and bascially stopped there. The extension added some menu items that don't work. Also, the documentation in other extensions say they can be installed through the extension manager, but that is not correct. First, I can't find them in the manager and every attempt to install an extension through it fails.
After that, I saw no purpose in trying to install more extensions as the system so far isn't working.

**Comment by asthomasdk** [comment]
Hi @haddow777,

Yes, you could this an alpha stage project. It is an open source version of our own internal project that we used to build the nodeSpeed development environment for the Spinups platform. The current version of the nodeSpeed IDE project is meant as a starter to try and get things going with involvement from others. As you have found, there are still a few kinks to sort out in this version which is outside the context of our own managed environment. 

I can see there are some permissions issues if you follow the simple docker based setup and use a data container for your projects, extensions etc. I will be pushing some scripts that can be used to set this. 

The extensions that are listed on the project are not published to npm or to the brackets registry. So you will have to install these manually for now. This is easily done using `git clone` in `/projects/.brackets-server/extensions/user`. You may need to run `npm install`for each extension after that. 

With regards to Preview, we have not been using the Brackets preview feature - so this is intentionally disabled. We have been using node projects (e.g. a simple express project to serve html files) that are running on port 3000 - and then use this port as the preview port. 

Once I have done some further testing locally,  will update the readme and push an update that will make it easier to get going with an initial build. 

Thanks for looking at this. I hope that with some feedback from us and updates to sort out the issues we find, that you will find the project useful - and maybe also help in moving it forward.

**Comment by asthomasdk** [comment]
Please see the updated readme with better explanations on some of the issues you have raised. 

I have also added a couple of scripts that can be used to set directory permissions on a docker data container and to install the suggested extensions using `git clone`. 

Hope this helps and gets you off to a better start with nodeSpeed IDE.
